### ISSUE TITLE
Difference between football associations and clubs

### ISSUE THREAD

**Issue by minaleebtu** [Bergmann97/DFB_Webapp#3]
I am sorry but I don't have good knowledge about football associations or clubs. Could you please let me know how the football association and football club are different? As far as I understood, an association can control or manage multiple football teams as shown in the example data. However, I am not sure about the football club.

**Comment by Bergmann97** [comment]
Normally a football association has a league like, i.e.,  the Bundesliga in Germany which includes 18 football clubs (i.e., FC Bayern München, Borussia Dortmund, ...). This means, that a football association that includes the Bundesliga has 18 football clubs.  In our app we are leaving the leagues, so that we have an overview of which clubs belong to which football association.
As a Data example in the app there should then be a football association that has a president that manages the association. The association than also has a number of football clubs as described above as a list or something like that, so that these clubs can be associated to this football association.
The football club does just manage the intern personalities, like a coach and the team, so 11+ players, as well as members that are just some persons that financially supporting the club and want to be part of it, but they don't have any rights to manage the club.
I hope this clearifies it a bit more.

**Comment by minaleebtu** [comment]
Thank you for the explanation. So as my understanding, for example in the sample data, FC Energie Cottbus is one of the football clubs and associated to Brandenburg football association, right? I was quite confused about the words 'football team' and 'football club'.
